
- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 19.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_19.x bionic main
    update_cache: yes

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: Install http-server
  npm:
    name: http-server
    global: yes

- name: Add service user Frontend
  user:
    name: "{{ frontend_user }}"
    create_home: no
    shell: /sbin/nologin

- name: Create directory
  file:
    path: "{{ frontend_path }}"
    state: directory

- name: Create directory
  file:
    path: "{{ logs_path }}"
    state: directory

- name: Create directory
  file:
    path: "{{ report_path }}"
    state: directory

- name: Download NEXUS artficats
  ansible.builtin.get_url:
    url: "{{ frontend_repository_url }}"
    dest: "{{ frontend_path }}"
    username: "{{ nexus_user }}"
    password: "{{ nexus_password }}"

- name: Unarchive a Sausage-store.tar.gz
  ansible.builtin.unarchive:
    src: "{{ frontend_path}}/sausage-store-{{ frontend_version}}.tar.gz"
    dest: "{{ frontend_path}}"
    remote_src: yes

- name: Add permission
  ansible.builtin.file:
    path: "{{ frontend_path }}"
    owner: "{{ frontend_user }}"
    group: "{{ frontend_user }}"
    mode: '0755'

- name: Copy unit-file
  template:
    src: "sausage-store-frontend.service.j2"
    dest: /etc/systemd/system/sausage-store-frontend.service

- name: Reloading systemd
  systemd:
    daemon_reload: true

- name: Start FRONTEND service
  service:
    name: sausage-store-frontend
    state: started
    enabled: true
