stages:
- deploy

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
before_script:
  - export KUBECONFIG=${KUBECONFIG}
script:
  - kubectl get pods
  - kubectl apply -f ./kubernetes/backend
  - kubectl apply -f ./kubernetes/backend-report
  - kubectl apply -f ./kubernetes/frontend
only:
    changes:
      - kubernetes/**/*


  

