backend:
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 30
    timeoutSeconds: 10 
    failureThreshold: 6
  replicas: 3
  revisionHistoryLimit: 15 
  strategyType: RollingUpdate
  rollingUpdate:
      maxUnavailable: 2
      maxSurge: "20%"
  image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-backend
  imagePullPolicy: Always
  ports:
    containerPort: 8080
    port: 8080
    protocol: TCP
  imagePullSecrets:
    name: docker-config-secret
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    minAllowed:
      cpu: 0m
      memory: 0Mi
    maxAllowed:
      cpu: 0.5
      memory: 500Mi


