# values.yaml
backend: # Это имя чарта из dependencies
  # Вместо latest правильнее использовать версию .Chart.AppVersion в шаблоне
  image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-backend
  appName: backend
  description: Sausage Store Backend Helm Chart
  containerName: "*"
  spec:
    replicas: 3
    revisionHistoryLimit: 15
    ports:
      port: 8080
      targetPort: 8080
      protocol: TCP 
  livenessProbe:
    path: /actuator/health
    initialDelaySeconds: 20
    periodSeconds: 30
    imeoutSeconds: 10 
    failureThreshold: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: "20%"
  imagePullSecrets:
    name: docker-config-secret
  env:
    spring_url: SPRING_DATASOURCE_URL
    spring_username: SPRING_DATASOURCE_USERNAME
    spring_password: SPRING_DATASOURCE_PASSWORD
    virtual_host: VIRTUAL_HOST
    mongo_uri: SPRING_DATA_MONGODB_URI
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      minAllowed:
        cpu: 0m
        memory: 0Mi
      maxAllowed:
        cpu: 0.5
        memory: 500Mi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits 

  


frontend:
  appName: frontend
  image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-frontend
  fqdn: std-013-60.k8s.praktikum-services.tech
  description: Sausage Store Frontend Helm Chart
  imagePullPolicy: Always
  ingressName: frontend-ingress
  spec:
    path: /
    pathType: Prefix
    ingressClassName: "nginx"
    replicas: 1
    revisionHistoryLimit: 15   
    affinity:
      key: app
      operator: In
    strategy:
      type: Recreate
    ports:
      protocol: TCP
      port: 80
      targetPort: 80
      containerPort: 1080
  volumes:
    name: nginx-conf
    mountPath: /etc/nginx/conf.d/
    configMap:
      items:
        key: nginx.conf
        path: default.conf
  imagePullSecrets:
    name: docker-config-secret
  env:
   defHost: DEFAULT_HOST




backend_report:
  image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-backend-report
  appName: backend-report
  ports:
    containerPort: 8888
  imagePullSecrets:
    name: docker-config-secret
  strategy:
    type: Recreate
  spec:
    imagePullPolicy: IfNotPresent
    minReplicas: 1
    maxReplicas: 5
  metrics:
    type: Resource
    name: cpu
    target:
      type: Utilization
      averageUtilization: 75
  env:
    db: DB
    port: PORT
