---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: sausage-frontend
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sausage-store
    env: "{{ .Values.environment }}" 
spec:
  replicas: 1
  revisionHistoryLimit: 15 
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями  
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
{{ toYaml .Values.spec | indent 6 }}
      containers:
      - image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
        name: {{ .Chart.Name }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        env:
          - name: DEFAULT_HOST
            value: backend
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 8 }}        
      volumes:
{{ toYaml .Values.volumes | indent 12 }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}