---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.frontend.ingressName }}
spec:
  # В кластере может быть несколько Ingress Controllers, мы используем NGINX
  ingressClassName: {{ .Values.frontend.spec.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.frontend.fqdn }}
  rules:
    # Хост определяет правило направления траффика по доменному имени
  - host: {{ .Values.frontend.fqdn }}
    http:
      # Для различных путей в URL можно указать различные бэкенд-сервисы
      paths:
      - path: {{ .Values.frontend.spec.path }}
        pathType: {{ .Values.frontend.spec.pathType }}
        backend:
          service:
            # Заранее создан сервис типа ClusterIP
            # Он выступает в качестве бэкенда нашего Ingress
            name: {{ .Values.frontend.appName }}
            port:
              # У сервиса может быть несколько портов, указываем нужный нам
              number: {{ .Values.frontend.ports.port }}
