---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: {{ .Values.frontend.ports.protocol }}
    port: {{ .Values.frontend.ports.port }}
    targetPort: {{ .Values.frontend.ports.targerPort }}
  

