---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.appName }}
  labels:
    app: {{ .Values.frontend.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontend.appName }}
  ports:
  - protocol: {{ .Values.frontend.ports.protocol }}
    port: {{ .Values.frontend.ports.port }}
    targetPort: {{ .Values.frontend.ports.targerPort }}
  

