---
apiVersion: v2
type: application
name: {{ .Values.backend-report.appName }}
description: {{  .Values.backend-report.description }}

version: {{ .Chart.version }}
appVersion: {{ .Chart.AppVersion }}
