---
apiVersion: v1
kind: Secret
metadata:
  name: backend-report
  labels:
    app: backend-report
data:
  port: ODg4OA== 
  db: bW9uZ29kYjovL3N0ZC0wMTMtNjA6VGVzdHVzcjEyMzRAcmMxYS14YjZxN3BtdzM2dDc3cnl6Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAxMy02MD90bHM9dHJ1ZSZ0bHNDYUZpbGU9WWFuZGV4SW50ZXJuYWxSb290Q0EuY3J0
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4TXkwMk1EcHlPV1F6TVRGSlFnPT0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJhM2RsWldwbFltOXZPa0p5TXpSclpEQjNiaUU9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
