---
apiVersion: v1
kind: Secret
metadata:
  name: backend
  labels:
    app: backend
data:
  db: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYi10eGVuamVvdDBxYmNibmgzLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDEzLTYw
  db_username: c3RkLTAxMy02MA==
  db_password: VGVzdHVzcjEyMzQ=
type: Opaque

---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4TXkwMk1EcHlPV1F6TVRGSlFnPT0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJhM2RsWldwbFltOXZPa0p5TXpSclpEQjNiaUU9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson

