---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями  
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gitlab.praktikum-services.ru:5050/<свой репо образа>/sausage-store/sausage-backend:<тег>
          imagePullPolicy: IfNotPresent
          env:
            - name: DEFAULT_HOST
              value: backend
          ports:
            - name: backend
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 6

  containers:
    - image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-frontend:latest
      name: frontend
      imagePullPolicy: IfNotPresent
      env:
        - name: DEFAULT_HOST
          value: backend
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: default.conf
      
      imagePullSecrets:
        - name: docker-config-secret 
