
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - image: gitlab.praktikum-services.ru:5050/<путь к репозиторию образа>:<тег образа>
      name: frontend
      imagePullPolicy: IfNotPresent
      env:
      
      ports:
        - name: backend
          containerPort: 1080
      livenessProbe:
         
        # перед исполнением первой проверки подождать 15 секунд, пока стартанёт бэкенд          
        initialDelaySeconds: 15
        # период выполнения проверки
        periodSeconds: 30
        # максимальное время выполнения проверки (по умолчанию 1 раз)
        timeoutSeconds: 2
        # сколько раз пробовать попытку, если она провалилась (по умолчанию 1 раз)
        failureThreshold: 6
  # чтобы Кубер мог скачивать образы из нашего GitLab Registry  
  imagePullSecrets:
    - name: docker-config-secret 
