---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.backend.appName }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Values.backend.appName }}
  updatePolicy:
    updateMode: {{ .Values.backend.updatePolicy.updateMode }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Values.backend.containerName }}
        minAllowed:
          cpu: {{ .Values.backend.resourcePolicy.containerPolicies.minAllowed.cpu }}
          memory: {{ .Values.backend.resourcePolicy.containerPolicies.minAllowed.memory }}
        maxAllowed:
          cpu: {{ .Values.backend.resourcePolicy.containerPolicies.maxAllowed.cpu }}
          memory: {{ .Values.backend.resourcePolicy.containerPolicies.maxAllowed.memory }}
        controlledResources: {{ .Values.backend.resourcePolicy.containerPolicies.controlledResources }}
        controlledValues: {{ .Values.backend.resourcePolicy.containerPolicies.controlledValues }}
