---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.appName }}
  labels:
    app: {{ .Values.backend.appName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port}}
      protocol: {{ .Values.backend.protocol }}
      targetPort: {{ .Values.backend.targetPort }}
  selector:
    app: {{ .Values.backend.appName }} 
