---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.spec.ports.port }}
      protocol: {{ .Values.backend.spec.ports.protocol }}
      targetPort: {{ .Values.backend.spec.ports.targetPort }}
  selector:
    app: {{ .Chart.Name }} 
