
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  replicas: 1
  # Стратегия развёртывания. Recreate — удалит сначала все старые Pod'ы 
  # Есть и более гибкая стратегии, например, RollingUpdate, которая будет обновлять Pod'ы порциями  
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-backend-report:latest
          name: backend-report
          imagePullPolicy: IfNotPresent
          env:
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: backend-report
                  key: db
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: backend-report
                  key: port
          ports:
            - name: backend-report
              containerPort: 8888
      imagePullSecrets:
      - name: docker-config-secret 
