---
apiVersion: v1
kind: Service
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  type: ClusterIP
  ports:
    - port: 8888 
      protocol: TCP
      targetPort: 8888 
  selector:
    app: backend-report

